apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-api
  name: java-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-api
    spec:
      containers:
      - image: docker.io/test12345mohit/java-api-build:latest
        name: java-api
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8082
status: {}
